// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_G4R_Ah0XuNFK0W3wt_HJIGaaVHr4Zls',
    appId: '1:443158351698:web:275cff043feb171958b48b',
    messagingSenderId: '443158351698',
    projectId: 'sumeruweb',
    authDomain: 'sumeruweb.firebaseapp.com',
    storageBucket: 'sumeruweb.firebasestorage.app',
    measurementId: 'G-ZG8D9KEEPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAuyof6kBBDJAyOiG7xgJtARcEAjFEvBM',
    appId: '1:443158351698:android:f357090a7632d50e58b48b',
    messagingSenderId: '443158351698',
    projectId: 'sumeruweb',
    storageBucket: 'sumeruweb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5v3SeqTa9SBZ4uVb4ZrhhaMLuN97nLtE',
    appId: '1:443158351698:ios:0e19148eb89ede1f58b48b',
    messagingSenderId: '443158351698',
    projectId: 'sumeruweb',
    storageBucket: 'sumeruweb.firebasestorage.app',
    iosBundleId: 'com.example.sumeruweb',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5v3SeqTa9SBZ4uVb4ZrhhaMLuN97nLtE',
    appId: '1:443158351698:ios:0e19148eb89ede1f58b48b',
    messagingSenderId: '443158351698',
    projectId: 'sumeruweb',
    storageBucket: 'sumeruweb.firebasestorage.app',
    iosBundleId: 'com.example.sumeruweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_G4R_Ah0XuNFK0W3wt_HJIGaaVHr4Zls',
    appId: '1:443158351698:web:d950e3c183f883c458b48b',
    messagingSenderId: '443158351698',
    projectId: 'sumeruweb',
    authDomain: 'sumeruweb.firebaseapp.com',
    storageBucket: 'sumeruweb.firebasestorage.app',
    measurementId: 'G-PEGRL8YBKJ',
  );
}
